import { Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const inter = Inter({
    subsets: ["latin"],
});

export const metadata = {
    title: "Shopiq",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${inter.className} ${geistMono.variable} antialiased`}
            >
                <Navbar />
                <main className="content flex-1">{children}</main>
                <Footer />
            </body>
        </html>
    );
}
